[package]
name = "setup-utils"
version = "0.3.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>", "The Aleo Team <hello@aleo.org>"]
edition = "2018"

[[bench]]
name = "io"
harness = false
required-features = ["phase1"]

[[bench]]
name = "math"
harness = false

[dependencies]
zexe_algebra = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra", version = "0.1.0" }
zexe_fft = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "ff-fft", version = "0.1.0", default-features = false }
zexe_r1cs_core = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "r1cs-core", version = "0.1.0" }

blake2 = { version = "0.8.1" }
blake2s_simd = { version = "0.5.11" }
cfg-if = { version = "0.1.10" }
crossbeam = { version = "0.8.0" }
num_cpus = { version = "1.12.0" }
rand = { version = "0.7.3" }
rand_chacha = { version = "0.2.1" }
rayon = { version = "1.4.1", optional = true }
rust-crypto = { version = "0.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
thiserror = { version = "1.0.11" }
tracing = { version = "0.1.21" }
typenum = { version = "1.11.2" }

[dev-dependencies]
phase1 = { path = "../phase1" }

zexe_algebra = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra", version = "0.1.0", features = ["bls12_377", "bw6_761"] }

criterion = { version = "0.3.1" }
rusty-hook = { version = "0.11.2" }

[features]
default = ["parallel"]
cli = ["parallel", "rust-crypto"]
wasm = ["rand/wasm-bindgen"]

parallel = ["rayon", "zexe_algebra/parallel", "zexe_fft/parallel"]
