[package]
name = "phase1"
version = "0.3.0"
authors = ["Sean Bowe", "Alex Vlasov", "The Aleo Team <hello@aleo.org>"]
description = "Communal zk-SNARK MPC for Public Parameters"
homepage = "https://github.com/AleoHQ/aleo-setup"
repository = "https://github.com/AleoHQ/aleo-setup"
license = "MIT/Apache-2.0"
edition = "2018"

[[bench]]
name = "phase1"
harness = false
required-features = ["benchmark"]

[dependencies]
setup-utils = { path = "../setup-utils", default-features = false }

zexe_algebra = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra", version = "0.1.0", features = ["derive"] }
zexe_algebra_core = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra-core", version = "0.1.0", optional = true, features = ["derive"] }

cfg-if = { version = "0.1.10" }
criterion = { version = "0.3", optional = true }
itertools = { version = "0.8.0" }
rand = { version = "0.7" }
rayon = { version = "1.3.0", optional = true }
tracing = { version = "0.1.17" }
tracing-subscriber = { version = "0.2.3" }
derivative = { version = "2", features = [ "use_core" ] }
snarkos-profiler = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-profiler" }

[dev-dependencies]
phase1 = { path = "./", features = ["testing"] }

zexe_algebra = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra", version = "0.1.0", features = ["full", "derive"] }
snarkos-posw = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-posw", default-features = false }
snarkos-errors = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-errors", default-features = false }
snarkos-curves = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-curves", default-features = false }
snarkos-marlin = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-marlin", default-features = false }
snarkos-models = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-models", default-features = false }
snarkos-utilities = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-utilities", default-features = false }
snarkos-objects = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-objects", default-features = false }
snarkos-algorithms = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-algorithms", default-features = false }
snarkos-gadgets = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-gadgets", default-features = false }
snarkos-polycommit = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-polycommit", default-features = false }
blake2 = { version = "0.8", default-features = false }

anyhow = { version = "1.0.31" }
num-traits = { version = "0.2.12" }
rusty-hook = { version = "0.11.2" }

[features]
default = ["cli"]
testing = ["parallel", "zexe_algebra_core", "snarkos-profiler/print-trace"]
parallel = ["rayon", "setup-utils/parallel", "zexe_algebra/parallel", "zexe_algebra_core/parallel"]
benchmark = ["criterion"]

cli = ["parallel", "setup-utils/cli"]
wasm = ["setup-utils/wasm"]

[[test]]
name = "aleo_compatibility"
path = "tests/aleo_compatibility.rs"
required-features = ["phase1/testing"]

[[test]]
name = "marlin"
path = "tests/marlin.rs"
required-features = ["phase1/testing", "cli"]

