#[development]
#address = "localhost"
#port = 8080
#workers = 2
#keep_alive = 5
#log = "normal"
#secret_key = [randomly generated at launch]
#limits = { forms = 32768 }
#
#[staging]
#address = "0.0.0.0"
#port = 8080
#workers = 4
#keep_alive = 5
#log = "normal"
#secret_key = [randomly generated at launch]
#limits = { forms = 32768 }
#
#[production]
#address = "0.0.0.0"
#port = 8080
#workers = 8
#keep_alive = 5
#log = "critical"
#secret_key = [randomly generated at launch]
#limits = { forms = 32768 }
